"""Fetch upcoming Houston comedy shows from the Ticketmaster Discovery API
and save them to shows.json. The API key is read from the environment
(set as a GitHub secret), never written in this file."""
import json, os, sys, time, urllib.parse, urllib.request

import re

VENUE_NAMES = {
    "Improv Comedy Club- Houston": "Houston Improv",
    "Toyota Center - TX": "Toyota Center",
}

def fix_text(s):
    """Repair garbled accents and quotes that Ticketmaster sometimes sends."""
    def rep(m):
        run = m.group(0)
        for cand in (run, run.replace("\u00e3", "\u00c3").replace("\u00e2", "\u00c2")):
            try:
                return cand.encode("latin-1").decode("utf-8")
            except Exception:
                pass
        return run
    s = re.sub(r"[\u0080-\u00ff]+", rep, s)
    s = re.sub(r"[\u0080-\u009f\u00c2]", "", s)
    return s.replace("\u00a0", " ").strip()

KEY = os.environ.get("TICKETMASTER_API_KEY")
if not KEY:
    sys.exit("Missing TICKETMASTER_API_KEY")

BASE = "https://app.ticketmaster.com/discovery/v2/events.json"
shows, page, total_pages = [], 0, 1

while page < total_pages and page < 5:  # up to ~1000 events
    q = urllib.parse.urlencode({
        "apikey": KEY, "city": "Houston", "stateCode": "TX",
        "classificationName": "comedy", "size": 200, "page": page,
        "sort": "date,asc",
    })
    with urllib.request.urlopen(f"{BASE}?{q}", timeout=30) as r:
        data = json.load(r)
    total_pages = data.get("page", {}).get("totalPages", 1)
    for e in data.get("_embedded", {}).get("events", []):
        start = e.get("dates", {}).get("start", {})
        if not start.get("localDate"):
            continue
        time_part = start.get("localTime", "19:00:00")
        venues = e.get("_embedded", {}).get("venues", [{}])
        imgs = sorted(e.get("images", []), key=lambda i: i.get("width", 0), reverse=True)
        img = next((i["url"] for i in imgs if i.get("ratio") == "16_9" and i.get("width", 0) <= 1100), None)
        prices = e.get("priceRanges", [])
        shows.append({
            "title": fix_text(e.get("name", "Comedy show")),
            "venue": VENUE_NAMES.get(fix_text(venues[0].get("name", "Houston")), fix_text(venues[0].get("name", "Houston"))),
            "start": f"{start['localDate']}T{time_part}",
            "price": prices[0].get("min") if prices else None,
            "url": e.get("url"),
            "img": img,
        })
    page += 1
    time.sleep(0.3)

# Remove duplicates: same venue and start time, with matching or overlapping titles.
# Prefer ticketmaster.com links.
def norm(t):
    return re.sub(r"\W+", "", t.lower())

unique = []
for sh in shows:
    n = norm(sh["title"])
    dup = None
    for u in unique:
        if u["start"] == sh["start"] and u["venue"] == sh["venue"]:
            un = norm(u["title"])
            if n == un or n in un or un in n:
                dup = u
                break
    if dup is None:
        unique.append(sh)
    elif "ticketmaster.com" in (sh["url"] or "") and "ticketmaster.com" not in (dup["url"] or ""):
        unique[unique.index(dup)] = sh
shows = unique

shows.sort(key=lambda s: s["start"])
with open("shows.json", "w") as f:
    json.dump({"updated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), "shows": shows}, f, indent=1)
# Build a browsable list of every act (soonest first) to help with picking.
import datetime
seen = {}
for sh in shows:
    seen.setdefault(sh["title"].lower(), sh)
lines = ["# ALL UPCOMING ACTS - rebuilt automatically twice a day. Do not edit this file.",
         "# To pick one, copy its line into picks.txt. Soonest shows come first."]
month = None
for sh in seen.values():
    m = datetime.datetime.strptime(sh["start"][:7], "%Y-%m").strftime("%B %Y")
    if m != month:
        lines += ["", f"# ----- {m} -----"]
        month = m
    lines.append(sh["title"])
with open("comedians.txt", "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Saved {len(shows)} shows")
